# Q.  Write a program to input eight numbers from the user and display all the unique 
#numbers (once).
sets=set()
n=input("Enter Number: ")
sets.add(int(n))
n=input("Enter Number: ")
sets.add(int(n))
n=input("Enter Number: ")
sets.add(int(n))
n=input("Enter Number: ")
sets.add(int(n))
n=input("Enter Number: ")
sets.add(int(n))
n=input("Enter Number: ")
sets.add(int(n))
n=input("Enter Number: ")
sets.add(int(n))
n=input("Enter Number: ")
sets.add(int(n))
print(sets)